### ISSUE TITLE
GOV.UK Frontend Inputs fail to render

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-frontend-jinja#40]
Trying to import and use GOV.UK Frontend text inputs 

```
 {{ govukInput({
     "label": {
        "text": 'testing'
     },
     "id": "email_address",
     "name": "email_address"
 })}}

```

It raises the following error:
`jinja2.exceptions.TemplateAssertionError: no filter named 'indent_njk'`

I think this is because in the text input component it uses two filters `indent` and `trim` to format the so that it is readable. (https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/input/template.njk#L16)

**Comment by lfdebrux** [comment]
This has been fixed, I'm going to release a new version with the fix.
